global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'python-app'
    static_configs:
      - targets: ['python-app:8000']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-proxy:80']
